networks:
  goexpert:



services:
  redis:
    hostname: redis
    container_name: redis
    restart: always
    image: redis:7.0.15-alpine3.20
    ports:
      - "6379:6379"
    networks:
      - goexpert
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    hostname: app
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - aleroxac/goexpert-ratelimiter:v1
    ports:
      - "8080:8080"
    networks:
      - goexpert
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

